### ISSUE TITLE
[clearml-server] PVC's are made even though services are disabled

### ISSUE THREAD

**Issue by lucasvandijck** [clearml/clearml-helm-charts#334]
### Describe the bug a clear and concise description of what the bug is.

I am deploying the clearml chart with the following values:

```
redis:
  enabled: false
mongodb:
  enabled: false
elasticsearch:
  enabled: false
```

However, ClearML is still deploying PVC's for these services, although they stay unused.

(I have tested both on a local microk8s cluster and AKS cluster)

### What's your helm version?

3.16.3

### What's your kubectl version?

1.29.9

### What's the chart version?

7.11.5

### Enter the changed values of values.yaml?

```
replicaCount: 1
fileserver:
  enabled: false
apiserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "api.clearml.xyz.be"
webserver:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostName: "app.clearml.xyz.be"
externalServices:
  redisHost: "redis-service"
  redisPort: 6379
redis:
  enabled: false
mongodb:
  enabled: false
elasticsearch:
  enabled: false
```
