### ISSUE TITLE
[clearml] Error when using redis in sentinel mode

### ISSUE THREAD

**Issue by killmeplz** [clearml/clearml-helm-charts#352]
### Describe the bug a clear and concise description of what the bug is.

How exactly clearml knows that it need to connect to redis sentinel in order to get the redis address?
I deploy redis with clearml chart using the following values. 
```
redis:
  master:
    name: "{{ .Release.Name }}-redis"
  architecture: replication
  replica:
    replicaCount: 3
  sentinel:
    enabled: true
```
However I get the error on the api server
`Action failed <500/0: tasks.create/v1.0 (You can't write against a read only replica.)`
I couldn't find any variables in helm chart to inform apiserver that it needs to connect to sentinel on 26379 port in order to get the master IP address.
So my question is what do I do wrong and is there a workaround for it (other than using standalone redis)? 

### What's your helm version?

v3.15.4

### What's your kubectl version?

v1.31.0

### What's the chart version?

7.14.3
