### ISSUE TITLE
[clearml] nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

### ISSUE THREAD

**Issue by Blarc** [clearml/clearml-helm-charts#360]
### Describe the bug a clear and concise description of what the bug is.

After searching the web for a while I figured I need to update nginx configuration. So I searched for nginx configuration in the containers and found this **crazy** hack:

![Image](https://github.com/user-attachments/assets/8ebdb867-34ac-4ced-a9d4-e6340f1665ab)

So the solution is:
```yaml
  webserver:
    extraEnvs:
      - name: COMMENT_IPV6_LISTEN
        value: "#"
```

I wonder if there is a better way? Otherwise, I'd would be good to document this somewhere.

### What's your helm version?

version.BuildInfo{Version:"3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"clean", GoVersion:"go1.22.9"}

### What's your kubectl version?

Client Version: v1.33.1 Kustomize Version: v5.6.0 Server Version: v1.26.13

### What's the chart version?

7.14.4

**Comment by HitogamiAG** [comment]
Hello,

according to container entrypoint `/opt/clearml/wrapper.sh`, there is env var `DISABLE_NGINX_IPV6` that overrides value for `COMMENT_IPV6_LISTEN` right before starting the nginx:

![Image](https://github.com/user-attachments/assets/015a5791-4a8c-460e-aad0-a6b48fb46bff)

I think a better solution will be:
```yaml
webserver:
  extraEnvs:
    - name: DISABLE_NGINX_IPV6
      value: "true"
```
